### ISSUE TITLE
Not used macros in application.c

### ISSUE THREAD

**Issue by findmyname666** [bigclownlabs/bcf-radio-soil-sensor#1]
Hello all,

File **application.c** contains these two macros:
```
#define SENSOR_TEMPERATURE_PUB_INTERVAL     (5 * 60 * 1000)
#define SENSOR_TEMPERATURE_PUB_DIFFERENCE 1.0f
```

Unfortunately I don't see any usage for them.

BR
Findmyname

**Comment by hubmartin** [comment]
They are obsolete, fixed.
Thanks.
